<?php
$npcImages = <<<EOD
ancient_crystal.png
asp_hatchlings.png
asp_mother.png
bio_scavenger.png
blood_amoeba.png
blue_crystal.png
ceylacennia.png
cyborg_manta.png
dreadscorp.png
drosera.png
energybees.png
energy_locust.png
energy_minnow.png
energy_sparker.png
eulerian.png
euryale.png
euryale_swarmlings.png
exocrab.png
feral_serpent.png
feral_serpent_1.png
feral_serpent_2.png
feral_serpent_3.png
frost_crystal.png
fuel_tanker.png
glowprawn.png
gorefang.png
gorefangling.png
gorefanglings.png
hidden_drug_stash.png
ice_beast.png
infected_creature.png
locust_hive.png
lucidi_mothership.png
lucidi_squad.png
lucidi_warship.png
manifestation_developed.png
manifestation_ripe.png
manifestation_verdant.png
medusa.png
medusa_swarmlings.png
mutated_medusa.png
nebula_locust.png
nebula_mole.png
nebula_serpent.png
oblivion_vortex.png
pirate_captain.png
pirate_experienced.png
pirate_famous.png
pirate_inexperienced.png
preywinder.png
rive_crystal.png
roidworm_horde.png
sarracenia.png
scorpion_fighter.png
shadow.png
slave_trader.png
smuggler_escorted.png
smuggler_lone.png
solar_banshee.png
space_clam.png
space_crystal.png
space_dragon_elder.png
space_dragon_queen.png
space_dragon_young.png
space_locust.png
space_maggot.png
space_maggot_mutated.png
space_snail.png
space_worm.png
space_worm_albino.png
space_worm_mutated.png
starclaw.png
stheno.png
stheno_swarmlings.png
wormhole.png
vyrex_assassin.png
vyrex_hatcher.png
vyrex_larva.png
vyrex_mutant_mauler.png
vyrex_stinger.png
x993_battlecruiser.png
x993_mothership.png
x993_squad.png
xalgucennia.png
z15_fighter.png
z15_repair_drone.png
z15_scout.png
z15_spacepad.png
z16_fighter.png
z16_repair_drone.png
EOD;
$npcImages = str_replace(array("\r", "\n"), "", $npcImages);
?>